import { USER_ROLES } from "@/constants";

export const PERMISSIONS = {
  SUBJECT_CREATE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
  SUBJECT_EDIT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  SUBJECT_DELETE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  CLASS_CREATE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  CLASS_EDIT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  CLASS_DELETE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  COURSE_CREATE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  COURSE_EDIT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  COURSE_DELETE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  BATCH_CREATE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  BATCH_EDIT: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],

  BATCH_DELETE: [USER_ROLES.ADMIN, USER_ROLES.SUPER_ADMIN],
} as const;
